# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Plugins (previously gems:)
plugins:
  - jekyll-include-cache